apiVersion: apps/v1
kind: Deployment

metadata:
  name: goserver
  labels:
    apps: goserver
  annotations:
    kubernetes.io/change-cause: "Deployment: goserver com imagem v5.1 e testando readnessProbe"

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "fermope/go-server:v5.1"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3 #De quanto em quanto tempo verifica
          failureThreshold: 1 #Quantas vezes pra falhar para continuar não enviando tráfego
          initialDelaySeconds: 10 # Quanto tempo inicial para iniciar as verificações
        envFrom:
        - configMapRef:
            name: goserver-env
        - secretRef:
            name: goserver-secret
        volumeMounts:
        - mountPath: "/go/myfamily"
          name: config
          readOnly: true
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: goserver-env
              key: NAME
        - name: AGE
          valueFrom:
            configMapKeyRef:
              name: goserver-env
              key: AGE
      volumes:
      - name: config
        configMap:
          name: configmap-family
          items:
          - key: members
            path: "family.txt"

