apiVersion: apps/v1
kind: Deployment

metadata:
  name: goserver
  labels:
    apps: goserver
  annotations:
    kubernetes.io/change-cause: "Deployment: goserver com imagem v5"

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "fermope/go-server:v5"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5 #De quanto em quanto tempo verifica
          failureThreshold: 3 #Quantas vezes pra falhar vai reiniciar
          timeoutSeconds: 1 #Quanto tempo deve demorar essa verificação, caso demore x segundos e não respondeu ainda, considere erro
          successThreshold: 1 # Quantas verificações de sucesso é considerado que é um sucesso
        envFrom:
        - configMapRef:
            name: goserver-env
        - secretRef:
            name: goserver-secret
        volumeMounts:
        - mountPath: "/go/myfamily"
          name: config
          readOnly: true
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: goserver-env
              key: NAME
        - name: AGE
          valueFrom:
            configMapKeyRef:
              name: goserver-env
              key: AGE
      volumes:
      - name: config
        configMap:
          name: configmap-family
          items:
          - key: members
            path: "family.txt"

