apiVersion: apps/v1
kind: Deployment

metadata:
  name: goserver
  labels:
    apps: goserver
  annotations:
    kubernetes.io/change-cause: "Deployment: goserver com imagem v1"

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "fermope/go-server:v1"

