apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: goserver
  labels:
    apps: goserver

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "fermope/go-server:v2"

